-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.orders
(
    order_id serial NOT NULL,
    user_id serial NOT NULL,
    carport_width numeric NOT NULL,
    carport_length numeric NOT NULL,
    date date NOT NULL,
    status boolean NOT NULL,
    price integer,
    CONSTRAINT orders_pkey PRIMARY KEY (order_id)
    );

CREATE TABLE IF NOT EXISTS public.part_variant
(
    part_variant_id serial NOT NULL,
    length integer NOT NULL,
    part_id serial NOT NULL,
    CONSTRAINT part_variant_pkey PRIMARY KEY (part_variant_id)
    );

CREATE TABLE IF NOT EXISTS public.parts
(
    part_id serial NOT NULL,
    part_name character varying COLLATE pg_catalog."default" NOT NULL,
    unit character varying COLLATE pg_catalog."default",
    price integer NOT NULL,
    CONSTRAINT parts_pkey PRIMARY KEY (part_id)
    );

CREATE TABLE IF NOT EXISTS public.parts_list
(
    parts_list_id serial NOT NULL,
    order_id serial NOT NULL,
    part_variant_id serial NOT NULL,
    amount integer,
    description character varying COLLATE pg_catalog."default",
    CONSTRAINT parts_list_pkey PRIMARY KEY (parts_list_id)
    );

CREATE TABLE IF NOT EXISTS public.users
(
    user_id serial NOT NULL,
    user_name character varying COLLATE pg_catalog."default" NOT NULL,
    user_password character varying COLLATE pg_catalog."default" NOT NULL,
    user_mail character varying COLLATE pg_catalog."default" NOT NULL,
    user_phonenumber character varying COLLATE pg_catalog."default" NOT NULL,
    user_role boolean NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (user_id)
    );

ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.part_variant
    ADD CONSTRAINT part_variant_part_id_fkey FOREIGN KEY (part_id)
    REFERENCES public.parts (part_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.parts_list
    ADD CONSTRAINT parts_list_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES public.orders (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.parts_list
    ADD CONSTRAINT parts_list_part_variant_id_fkey FOREIGN KEY (part_variant_id)
    REFERENCES public.part_variant (part_variant_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;

END;

-- Insert data into parts
INSERT INTO public.parts (part_id, part_name, unit, price) VALUES
                                                               (1, '97x97 mm. trykimp. Stolpe', 'stk', 42),
                                                               (2, '45x195 mm. spærtræ ubh.', 'stk', 62);

-- Insert data into part_variant
INSERT INTO public.part_variant (part_variant_id, length, part_id) VALUES
                                                                       (1, 300, 1),
                                                                       (2, 240, 2),
                                                                       (3, 270, 2),
                                                                       (4, 300, 2),
                                                                       (5, 330, 2),
                                                                       (6, 360, 2),
                                                                       (7, 390, 2),
                                                                       (8, 420, 2),
                                                                       (9, 450, 2),
                                                                       (10, 480, 2),
                                                                       (11, 510, 2),
                                                                       (12, 540, 2),
                                                                       (13, 570, 2),
                                                                       (14, 600, 2);