@startuml
!pragma layout smetana

User --* Order
Order --* Carport
Carport --* Part

Class User {
- int id
- String username
- String password
- String email
- String phoneNumber
- boolean isAdmin
}

Class Order {
- int id
- int price
- Carport carport
- boolean status
}

Class Part {
- int id
- int amount
- int length
- int unit
}

Class Carport {
- ArrayList <Part> partList
}

Package util {
Class Calculator

Class CarportMapper{

}

Class OrderMapper{
+Order getOrder(int id)
+void insertOrder(Order order)
+List<Order> getAllOrders()
}

Class PartMapper{
+Part getPartByID(int id)
}

Class UserMapper{
+User getUserByEmail(String email)
+User getUserByID(int id)
+void createUser(String email, String password, String phoneNumber, String name)
}

Class CarportController{

}

Class OrderController{
+void OrderCreate(Context ctx)
}

Class PartController{

}

Class UserController{
+void loginUser(Context ctx)
+void registerUser(Context ctx)
+void logout(Context ctx)
}

}
@enduml