@startuml
!pragma layout smetana

User --* Order
Order --* Carport
Carport --* Part

Class User {
- int id
- String username
- String password
- String email
- String phoneNumber
- boolean isAdmin

}

Class Order {
- int id
- int price
- Carport carport
- boolean status
}

Class Part {
- int id
- int amount
- int length
- int unit
}

Class Carport {
- ArrayList <Part> partList
}

Package util {
Class Calculator

Class CarportMapper{

}

Class OrderMapper{

}

Class PartMapper{

}

Class UserMapper{

}

Class CarportController{

}

Class OrderController{

}

Class PartController{

}

Class UserController{

}

}
@enduml